version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm" 
    # Files stored in repository root
    directory: "/" 
    
    # Allow up to 10 open pull requests for maven dependencies
    open-pull-requests-limit: 10
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    # Disable rebasing for pull requests
    rebase-strategy: "disabled"
    # Add reviewers