on:
  push:
    branches:
      - master

name: Release 

jobs:
  semantic_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.RELEASE_USER }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#gintaa-github'
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: ":rocket: Released!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
