on:
  push:
    branches:
      - master

name: Release | Deploy

jobs:
  semantic_release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#gintaa-github'
          mention: 'here'
          if_mention: failure,cancelled
          status: ${{ job.status }}
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: '${{ job.status }}' === 'success' ? ':rocket: Released!' : '${{ job.status }}' === 'failure' ? ':boom: Failed!!!' : ':warning: Warned!!',
                title: 'CI Result',
                fields: [{
                  title: 'repo',
                  value: `process.env.AS_REPO`,
                  short: true
                },
                {
                  title: 'message',
                  value: `process.env.AS_MESSAGE`,
                  short: true
                },
                {
                  title: 'commit',
                  value: `process.env.AS_COMMIT`,
                  short: false
                },
                {
                  title: 'author',
                  value: `process.env.AS_AUTHOR`,
                  short: true
                },
                {
                  title: 'action',
                  value: `process.env.AS_ACTION`,
                  short: false
                },
                {
                  title: 'job',
                  value: `process.env.AS_JOB`,
                  short: true
                },
                {
                  title: 'took',
                  value: `process.env.AS_TOOK`,
                  short: false
                },
                {
                  title: 'eventName',
                  value: `process.env.AS_EVENT_NAME`,
                  short: true
                },
                {
                  title: 'ref',
                  value: `process.env.AS_REF`,
                  short: false
                },
                {
                  title: 'workflow',
                  value: `process.env.AS_WORKFLOW`,
                  short: false
                }]
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
  firebase_deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        run: echo "Deploy to firebase"
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#general'
          mention: 'here'
          if_mention: failure,cancelled
          status: ${{ job.status }}
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: '${{ job.status }}' === 'success' ? ':shipit: https://asconsoftech.com' : '${{ job.status }}' === 'failure' ? ':boom: Failed!!!' : ':warning: Warned!!',
                title: 'CI Result',
                fields: [{
                  title: 'repo',
                  value: `process.env.AS_REPO`,
                  short: true
                },
                {
                  title: 'message',
                  value: `process.env.AS_MESSAGE`,
                  short: true
                },
                {
                  title: 'commit',
                  value: `process.env.AS_COMMIT`,
                  short: false
                },
                {
                  title: 'author'
                  value: `process.env.AS_AUTHOR`,
                  short: true
                },
                {
                  title: 'action',
                  value: `process.env.AS_ACTION`,
                  short: false
                },
                {
                  title: 'job',
                  value: `process.env.AS_JOB`,
                  short: true
                },
                {
                  title: 'took',
                  value: `process.env.AS_TOOK`,
                  short: false
                },
                {
                  title: 'eventName',
                  value: `process.env.AS_EVENT_NAME`,
                  short: true
                },
                {
                  title: 'ref',
                  value: `process.env.AS_REF`,
                  short: false
                },
                {
                  title: 'workflow',
                  value: `process.env.AS_WORKFLOW`,
                  short: false
                }]
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
