on:
  release:
    types:
      - published

name: Firebase Deployment 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        run: echo "Deploy to firebase"
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#gintaa-github'
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: ":shitit: Our website is updated! Enjoy https://asconsoftech.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
