on:
  pull_request:
    branches:
      - master
      - develop
    
name: DangerJS | Sonarqube

jobs:
  check_1:
    if: github.actor != 'dependabot-preview'
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.actor }}

  check_2:
    if: github.actor != 'dependabot'
    name: Sonarqube Analysis
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.actor }}
